spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: booking-group
  jackson:
    default-property-inclusion: non_null
  application:
    name: UberBookingService
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/uber_db_local}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Nasir@02}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true